language: objective-c
xcode_sdk: 7.1
notifications:
  email: false
rvm:
- 2.1.1
branches:
  only:
  - master
  - /with\-ci$/
git:
  submodules: false
env:
  global:
  - SAUCE_REST_ROOT=https://saucelabs.com/rest/v1
  - APPIUM_HOST=ondemand.saucelabs.com
  - APPIUM_PORT=80
  - SAUCE_USERNAME=appium
  - IOS_CONCURRENCY=30
  - ANDROID_CONCURRENCY=30
  - SELENDROID_CONCURRENCY=10
  - GAPPIUM_CONCURRENCY=10
  # below is SAUCE_ACCESS_KEY encrypted
  - secure: GXGFbQptLEsKlaWnpOL2EB9hqQ4XBT6tqg7REt5j1h1jYBsfHQHSgSLt1jpzOF5kooXVbw2K7IrZyNVBXEUHR00Hp6O72FBOd+SSj8uPCJBLjAOaJWs0ZtujqGHwHpe6gadFfn0L7q0ffoV5OJVeNHHcuw4f9BaA78fTFNfm1jE=
  - HTTP_RETRIES=5
  - HTTP_RETRY_DELAY=5000
  - DEBUG_CONNECTION=1
  - MOCHA_INIT_TIMEOUT=600000
  - LAUNCH_TIMEOUT='{"global":90000,"afterSimLaunch":30000}'
  matrix:
  - CI_CONFIG=unit
  - CI_CONFIG=android
  - CI_CONFIG=ios
  - CI_CONFIG=gappium
  - CI_CONFIG=selendroid
before_script:
- gem install --no-rdoc --no-ri appium_doc_lint
- "./ci/installers/install-node.sh"
- "echo Node.js version: `node -v`"
- npm install -g jshint grunt-cli mocha
- npm install
- "./ci/before_script_extra.sh"
script:
- "./ci/script.sh"
